### ISSUE TITLE
[PE-D] Add package will not detect tokens if there is no space in between

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S2-CS2103-W17-3/tp#100]
As seen in picture, i don't think you want to allow the user to do this.

![image.png](https://raw.githubusercontent.com/putaojuice/ped/main/files/4611e71b-bf02-4261-a53b-5d4789d72623.png)

-------------
Labels: `type.FeatureFlaw` `severity.High`
original: putaojuice/ped#8

**Comment by leeyiheng12** [comment]
Hello, this is not limited to the add package command, but all commands.

With the exception of special fields (e.g. name, where we only allow alphanumeric characters), we do not usually restrict the values that a user can key in. In this case, while a value (e.g. the name of a package description to be added) may contain what looks like a token ("i/"), we will not sanitise it in the event that it is the intended value the user wishes to input.

As a side note, this reason is probably why the original AB3 (and the commands it came with, e.g. `add`), allows this behaviour as well.
